### PR TITLE
Handle entities+parens in URLs

### PR DESCRIPTION
**Pull request by shajith**
Calling autolink_delim multiple times instead of just once, until we find no more delimiters.

cc: @staugaard @jcheatham: This attempts to address the curious case of https://zendesk.airbrake.io/projects/88941/groups/1491395038594651826/notices/1491395136858806004

### CODE REVIEW

**Comment by staugaard** [comment]
:+1:

**Comment by staugaard** [comment]
:chicken:

**Comment by shajith** [comment]
Talked to @jcheatham about potentially not needing to iterate, but just doing it one more time. Will test that theory and close this out.

**Comment by shajith** [comment]
@jcheatham: I believe we talked ourselves into not changing anything here. Care for a plus-one?

**Comment by jcheatham** [comment]
Oh, did we?  Thought you were going to test the "iterate until stable" approach, though I'm fine either way :) :+1: and if it comes up we'll re-examine it at that time.

**Comment by shajith** [comment]
the "iterate until stable" approach will definitely work (in that it will produce correct output), though I wasn't sure if we want this to be open-ended.

**Pull request merged**
